config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :questions, only: %i[show index]
  resources :survey_responses, only: %i[show index]
  resources :creative_qualities, only: [:index]

  root to: 'creative_qualities#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question_choice
  belongs_to :survey_response

  validates :question_choice, presence: true
  validates :survey_response, presence: true

  delegate :question, to: :question_choice
  delegate :score_for, to: :question_choice
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creative_quality.rb
# frozen_string_literal: true

class CreativeQuality < ApplicationRecord
  has_many :question_choices, inverse_of: :creative_quality

  validates :name, :description, :color, presence: true

  def max_score(questions: nil)
    questions.nil? ? questions = Question.all : questions
    questions.sum { |q| q.max_for(self) }
  end

  def normalized_score(my_raw: nil, my_max: nil)
    my_raw.nil? ? my_raw = raw_total : my_raw
    my_max.nil? ? my_max = max_total : my_max
    (my_raw.fdiv(my_max) * 100.0).to_i.clamp(-100, 100)
  end

  def raw_total(surveys: nil)
    surveys.nil? ? surveys = SurveyResponse.includes(answers: :question_choice).all : surveys
    surveys.sum { |survey| survey.raw_score(self) }
  end

  def max_total(n_surveys: nil)
    n_surveys.nil? ? n_surveys = SurveyResponse.count : n_surveys
    max_score * n_surveys
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :question_choices, inverse_of: :question

  validates :title, presence: true

  accepts_nested_attributes_for(:question_choices)

  def max_for(quality)
    question_choices.max_by { |choice| choice.score_for(quality) }
                    .score_for(quality)
  end
end

app/models/question_choice.rb
# frozen_string_literal: true

class QuestionChoice < ApplicationRecord
  belongs_to :question, inverse_of: :question_choices
  belongs_to :creative_quality, inverse_of: :question_choices

  has_many :answers
  has_many :survey_responses, through: :answers

  validates :text, :question, :creative_quality, presence: true
  validates :score, numericality: { only_integer: true }

  def score_for(quality)
    quality == creative_quality ? score : 0
  end
end

app/models/survey_response.rb
# frozen_string_literal: true

class SurveyResponse < ApplicationRecord
  has_many :answers

  validates :first_name, presence: true
  validates :last_name, presence: true

  delegate :count, to: :answers, prefix: true

  def display_name
    "#{first_name} #{last_name}"
  end

  def completed?
    answers_count == Question.count
  end

  def raw_score(quality)
    answers.sum { |a| a.score_for(quality) }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creative_qualities_controller.rb
# frozen_string_literal: true

class CreativeQualitiesController < ApplicationController
  include ApplicationHelper
  def index
    @creative_qualities = CreativeQuality.all
    respond_to do |format|
      format.html
      format.json { render json: mock_creative_quality_scores }
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  def show
    @question = Question.includes(:question_choices).find(params[:id])
  end

  def index
    @questions = Question.order(:id)
  end
end

app/controllers/survey_responses_controller.rb
# frozen_string_literal: true

class SurveyResponsesController < ApplicationController
  def show
    @survey_response = SurveyResponse
                       .includes(
                         answers: [
                           question_choice: [
                             question: :question_choices
                           ]
                         ]
                       )
                       .find(params[:id])
  end

  def index
    @survey_responses = SurveyResponse.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def mock_creative_quality_scores
    scores = [67, -25, 50]
    data = []

    CreativeQuality
      .limit(3)
      .each_with_index do |creative_quality, i|
      data << creative_quality.as_json.merge(
        score: scores[i]
      )
    end

    data
  end
end

app/views/creative_qualities/index.html.erb
<!-- This is where the React app gets rendered -->
<div id="react-root">
  <!-- currently just rendering H2 title -->
</div>

<div class="qualities">
  <div class="col-md-12">
    <div class="row">
      <%= @creative_qualities.find_each do |creative_quality| %>
        <div class="col-md-4">
          <div class="panel panel-<%= creative_quality.name %>">
            <div class="panel-heading">
              <%= creative_quality.name %>
            </div>

            <div class="panel-body">
              <div class="quality quality-<%= creative_quality.name %>"></div>

              <div class="score">
                <small>your score:</small>
                  <%= creative_quality.normalized_score %>
              </div>

              <p>
                <%= creative_quality.description %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div style="padding: 100px 0;">
  <hr>

  <small class="text-muted">
    Thoughtfully designed by IDEO in California.
  </small>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Creative Difference', root_path, class: 'navbar-brand' %>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="navbar-nav nav">
        <li>
          <%= link_to 'Questions', questions_path %>
        </li>

        <li>
          <%= link_to 'Survey Responses', survey_responses_path %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Creative Difference – IDEO</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notifications' %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/questions/_header.html.erb
<h3>
  <div>
    <strong>
      <%= "Question #{question.id}" %>
    </strong>
  </div>

  <%= question.title %>
</h3>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      Questions
    </h2>

    <table class="table">
      <tbody>
        <% @questions.find_each do |question| %>
          <tr>
            <td>
              <strong>
                <%= question.id %>.
              </strong>
            </td>

            <td>
              <%= truncate(question.title, length: 75) %>
            </td>

            <td>
              <%= link_to 'View', question_path(question), class: 'btn btn-default btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-7">
    <%= render 'questions/header', question: @question %>

    <hr>

    <h3>
      Choices
    </h3>

    <%= bootstrap_form_for(@question) do |question_form| %>
      <table class="table">
        <% @question.question_choices.each_with_index do |question_choice, index| %>
          <% hide_label = index > 0 %>

          <%= question_form.fields_for(:question_choices, question_choice) do |choice_fields| %>
            <tr>
              <td>
                <%= choice_fields.text_field :text, readonly: true, hide_label: hide_label %>
              </td>

              <td>
                <%= choice_fields.select :creative_quality_id, options_for_select(CreativeQuality.pluck(:name, :id)), { hide_label: hide_label }, { disabled: true } %>
              </td>

              <td>
                <%= choice_fields.text_field :score, readonly: true, hide_label: hide_label %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>

      <div class="text-right">
        <%= question_form.submit 'Update Choices', disabled: true %>
      </div>
    <% end %>
  </div>
</div>

app/views/survey_responses/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2>
      Survey Responses
    </h2>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Completed?</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @survey_responses.each do |survey_response| %>
          <tr>
            <td>
              <%= truncate(survey_response.display_name, length: 90) %>
            </td>

            <td>
              <% if survey_response.completed? %>
                Yes
              <% else %>
                <span class="text-danger">No</span>
              <% end %>
            </td>

            <td>
              <%= link_to 'View', survey_response, class: 'btn btn-default btn-xs' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/survey_responses/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>
          <%= @survey_response.display_name %>
        </h3>
      </div>

      <div class="panel-body">
        Completed
        <%= @survey_response.answers_count %>
        of
        <%= Question.count %>
        questions
      </div>
    </div>

    <hr>

    <% CreativeQuality.all.each do |quality| %>
      <strong><%= quality.name %></strong><br>
        <ul>
          <li><%= "Raw score: #{@survey_response.raw_score(quality)}"%></li>
          <li><%= "Max score: #{quality.max_score}"%></li>
        </ul>
    <% end %>

    <% @survey_response.answers.each do |answer| %>
      <%= render 'questions/header', question: answer.question %>

      <table class="table table-bordered">
        <% answer.question.question_choices.each do |question_choice| %>
          <tr>
            <td>
              <% if question_choice == answer.question_choice %>
                <strong>
                  <%= question_choice.text %>
                  <br>
                  <span class=<%= question_choice.score > 0 ? "text-success" :
                                  question_choice.score == 0 ? "text-primary" :
                                  "text-danger" %>>
                    <%="#{question_choice.creative_quality.name}: #{question_choice.score} " %>
                  </span>
                </strong>
              <% else %>
                <span class="text-muted">
                  <%= question_choice.text %>
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>